In [6]:
import numpy as np

In [19]:
A = np.arange(6).reshape(3,2)

In [20]:
B = np.arange(6).reshape(3,2)

In [21]:
print(A)
print(B)

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [22]:
print(A*B)

[[ 0  1]
 [ 4  9]
 [16 25]]


In [23]:
print(A+B)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [24]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])